import 'package:dio/dio.dart';
import 'package:relosnews/Model/registerclass.dart';
class registerservice{
  var dio=Dio();
  Future<Autogenerated> fetchdata5(Object data) async {
    try {
      var response = await dio.post(
          "https://news-project-data-2.onrender.com/users/register",
          data: data);
      if (response.statusCode == 200) {
        return Autogenerated.fromJson(response.data);
      }
      else {
        throw Exception("invald");
      }
    }
    catch(err){
      throw Exception("$err");
    }
  }
}

